apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-rating-predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-rating-predictor
  template:
    metadata:
      labels:
        app: restaurant-rating-predictor
    spec:
      containers:
        - name: restaurant-rating-predictor
          image: dhruvrs/restaurant-rating-predictor:latest
          ports:
            - containerPort: 8005  
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 10
