apiVersion: v1
kind: Service
metadata:
  name: restaurant-rating-service
spec:
  selector:
    app: restaurant-rating-predictor
  ports:
    - port: 8005
      targetPort: 8005
      nodePort: 30008
  type: NodePort  
